### ISSUE TITLE
PID vanish timeout causes "Local variable 'x' referenced before assignment"

### ISSUE THREAD

**Issue by dsschneidermann** [gdraheim/docker-systemctl-replacement#122]
https://github.com/gdraheim/docker-systemctl-replacement/blob/03e8582d8096c0c5261b2261b892348504ce9553/files/docker/systemctl3.py#L3626

Fix is replacing 'x' here with 'timeout', if that's the intended info to emit. I'm not sure what's the point of "%s." in the log lines vs using "%ss", where I'm guessing "s" denotes seconds, so I'll add this "%ss" to my PR.

For completeness, here is the trace I hit
```
backend_1            | Traceback (most recent call last):                                                                                                                                                                
backend_1            |   File "/usr/bin/systemctl", line 6460, in <module>
backend_1            |     result = command_func()
backend_1            |   File "/usr/bin/systemctl", line 5525, in system_default
backend_1            |     return self.start_system_default(init = init)
backend_1            |   File "/usr/bin/systemctl", line 5537, in start_system_default
backend_1            |     self.stop_system_default()
backend_1            |   File "/usr/bin/systemctl", line 5556, in stop_system_default
backend_1            |     services = self.stop_target_system(target)
backend_1            |   File "/usr/bin/systemctl", line 5562, in stop_target_system
backend_1            |     self.stop_units(services)
backend_1            |   File "/usr/bin/systemctl", line 3419, in stop_units
backend_1            |     if not self.stop_unit(unit):
backend_1            |   File "/usr/bin/systemctl", line 3430, in stop_unit
backend_1            |     return self.stop_unit_from(conf)
backend_1            |   File "/usr/bin/systemctl", line 3441, in stop_unit_from
backend_1            |     return self.do_stop_unit_from(conf)
backend_1            |   File "/usr/bin/systemctl", line 3444, in do_stop_unit_from
backend_1            |     return self.do_stop_service_from(conf)
backend_1            |   File "/usr/bin/systemctl", line 3513, in do_stop_service_from
backend_1            |     if self.wait_vanished_pid(pid, timeout):
backend_1            |   File "/usr/bin/systemctl", line 3621, in wait_vanished_pid
backend_1            |     logg.info("wait for PID %s failed (%s.)", pid, x)
backend_1            | UnboundLocalError: local variable 'x' referenced before assignment
```

**Comment by gdraheim** [comment]
Checking on the patch I just wondered if it would be better to block the code getting into the wait-loop in the first place. A zero-timeout does surely have special implications.

In many cases about start/stop timeout I did also make sure that there is a minimal timeout. I am not sure why it did not kick in here - or if it would be useful.
