### ISSUE TITLE
Install to Centos6.8

### ISSUE THREAD

**Issue by 1392273211** [gdraheim/docker-systemctl-replacement#169]
I installed to Centos6.8 and wrote a startup script using Python system ctl. py to manage the error Traceback (most recent call last) during startup

File "/usr/bin/systemctl", line 6808, in<module>

Sys. exit (run (command, * modules))

File "/usr/bin/systemctl", line 6564, in run

Exitcode=is_ Not_ OK (systemctl. start_modules (* modules))

File "/usr/bin/systemctl", line 2889, in start_ Modules

Return self.start_ Units (units, init) and found_ All

File "/usr/bin/systemctl", line 2899, in start_ Units

If not self.start_ Unit:

File "/usr/bin/systemctl", line 2917, in start_ Unit

Return self.start_ Unit_ From (conf)

File "/usr/bin/systemctl", line 2932, in start_ Unit_ From

Return self.do_ Start_ Unit_ From (conf)

File "/usr/bin/systemctl", line 2935, in do_ Start_ Unit_ From

Return self.do_ Start_ Service_ From (conf)

File "/usr/bin/systemctl", line 3021, in do_ Start_ Service_ From

Self. write_ Status_ From (conf, MainPID=forkpid)

File "/usr/bin/systemctl", line 1933, in write_ Status_ From

Content="{}={} n". format (key, str (value))

ValueError: zero length field name in format

**Comment by gdraheim** [comment]
This looks like some old version of systemctl.py - can you clarify?
