### ISSUE TITLE
Does not work in CentOS 7? ("bad ini line")

### ISSUE THREAD

**Issue by onlyjob** [gdraheim/docker-systemctl-replacement#2]
~~~~
bash-4.2# systemctl start rsyslog
Traceback (most recent call last):
  File "/usr/local/bin/systemctl", line 2054, in <module>
    result = command_func(*modules)
  File "/usr/local/bin/systemctl", line 845, in start_of_units
    elif not self.start_unit(unit):
  File "/usr/local/bin/systemctl", line 849, in start_unit
    conf = self.load_unit_conf(unit)
  File "/usr/local/bin/systemctl", line 483, in load_unit_conf
    data = self.load_sysd_unit_conf(module)
  File "/usr/local/bin/systemctl", line 497, in load_sysd_unit_conf
    unit.read_sysd(path)
  File "/usr/local/bin/systemctl", line 245, in read_sysd
    raise Exception("bad ini line")
Exception: bad ini line
~~~~

**Comment by gdraheim** [comment]
I have created testcase 8002 ... this revealed that the rsyslog.services uses a ";" to comment out a line.

I have extended the unit file parser for that.

./testcase.py test_8002 -vv

**Comment by onlyjob** [comment]
Thank you for fixing this problem. All good. :)
