### ISSUE TITLE
postgresql-setup fails on "systemctl show -p Environment"

### ISSUE THREAD

**Issue by gdraheim** [gdraheim/docker-systemctl-replacement#39]
Installed on CentOS7 = postgresql-server-9.2.23-3.el7_4.x86_64

Running /usr/bin/postgresql-setup initdb

ERROR: `failed to find PGDATA setting in postgresql.service`

Reason: this section from "postgresql-setup":

    # this parsing technique fails for PGDATA pathnames containing spaces,
    # but there's not much I can do about it given systemctl's output format...
    PGDATA=`systemctl show -p Environment "${SERVICE_NAME}.service" |
                    sed 's/^Environment=//' | tr ' ' '\n' |
                    sed -n 's/^PGDATA=//p' | tail -n 1`
    if [ x"$PGDATA" = x ]; then
        echo "failed to find PGDATA setting in ${SERVICE_NAME}.service"
        exit 1
    fi

**Comment by gdraheim** [comment]
> systemctl show postgresql.service
    INFO:systemctl:EXEC BEGIN /usr/bin/systemctl show postgresql.service --system
    INFO:systemctl:try read unit postgresql.service
    Id=postgresql.service
    Names=postgresql.service
    Description=PostgreSQL database server
    MainPID=0
    SubState=dead
    ActiveState=inactive
    LoadState=loaded
    UnitFileState=disabled
    TimeoutStartUSec=3min 20s
    TimeoutStopUSec=3min 20s
    Environment=PGPORT=5432 PGDATA=/var/lib/pgsql/data

    > systemctl show postgresql.service -p Environment
    INFO:systemctl:EXEC BEGIN /usr/bin/systemctl show postgresql.service --system
    INFO:systemctl:try read unit postgresql.service
    Environment=PGPORT=5432 PGDATA=/var/lib/pgsql/data

**Comment by gdraheim** [comment]
Checking into the execution of postgresql-setup

    + systemctl show -p Environment postgresql.service
    Traceback (most recent call last):
      File "/usr/bin/systemctl", line 4155, in <module>
        loggfile = logging.FileHandler(_systemctl_extra_log)
      File "/usr/lib64/python2.7/logging/__init__.py", line 902, in __init__
        StreamHandler.__init__(self, self._open())
      File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open
        stream = open(self.baseFilename, self.mode)
    IOError: [Errno 13] Permission denied: '/var/log/systemctl.log'

actually, we can find that the command will restart itself as the postgres-user when it finds to be root.

    if test "$(id -u)" -eq 0; then
        exec $SU -s /bin/sh postgres -c "$cmd"
    fi
    test "$(id -u)" -eq 0 && exit 1

**Comment by gdraheim** [comment]
So as a workaround, the centar /var/log file is only written when writable. Most people doing some docker deployment will have the logfile owned by root and world non-writable, so you can not see any debug log lines in there - atleast for programs like postgresql show do the switch-user themselves.

Anyone who do still want to see debug logs, will have to switch the ownership of the log file or to make it word writable.
