### ISSUE TITLE
`ExecStopPost` executed on `stop` when service is not running

### ISSUE THREAD

**Issue by onlyjob** [gdraheim/docker-systemctl-replacement#6]
`systemctl stop myservice` executes `ExecStopPost` handler unconditionally...

For example I have the following error printed to console when I attempt to stop not running service:

~~~~
ERROR:systemctl:returncode 1
 /usr/bin/pkill -f ${DAEMON}
Traceback (most recent call last):
  File "/usr/local/bin/systemctl", line 2437, in <module>
    result = command_func(*modules)
  File "/usr/local/bin/systemctl", line 1193, in stop_of_units
    elif not self.stop_unit(unit):
  File "/usr/local/bin/systemctl", line 1201, in stop_unit
    return self.stop_unit_from(conf)
  File "/usr/local/bin/systemctl", line 1286, in stop_unit_from
    subprocess_wait(cmd, env, check=check)
  File "/usr/local/bin/systemctl", line 396, in subprocess_wait
    raise Exception("command failed")
Exception: command failed
~~~~

**Comment by gdraheim** [comment]
That seems to be an undocumented feature, I have only found a hint on such a behaviour for the oneshoot-services. I did also see quite some code around where there is first a query on the status-unit before issuing start-unit / stop-unit. (notable Ansible's "service" module).

Do you have a hint on documentation where the relation of is-active-unit and start-unit is explained.

So far I have only added a documentation hint for checking more deeply later. [master e1bdd61]

**Comment by gdraheim** [comment]
ExecStopPost is meant to cleanup, so it may be wisest to  not just let it fail.

I'll moving a more detail stop-behaviour on to version 1.1 as the current systemctl.py script works reasonably well.

**Comment by gdraheim** [comment]
note that a "systemctl.py stop service" will always execute ExecStop and ExecStopPost in the current implemention. In order to avoid that one would need to have a state model for the services with possible transitions and actions that are attached to it. AFAIK this is not documented anywhere.
