### ISSUE TITLE
Can not start docker, will get the FileNotFoundError.

### ISSUE THREAD

**Issue by amaothree** [gdraheim/docker-systemctl-replacement#87]
Guest: Arch Linux-WSL
Command: systemctl start docker
Error get: 
```
Traceback (most recent call last):
  File "/usr/sbin/systemctl", line 4521, in <module>
    result = command_func(*modules)
  File "/usr/sbin/systemctl", line 1755, in start_modules
    return self.start_units(units, init) and found_all
  File "/usr/sbin/systemctl", line 1765, in start_units
    if not self.start_unit(unit):
  File "/usr/sbin/systemctl", line 1783, in start_unit
    return self.start_unit_from(conf)
  File "/usr/sbin/systemctl", line 1793, in start_unit_from
    return self.do_start_unit_from(conf)
  File "/usr/sbin/systemctl", line 1909, in do_start_unit_from
    notify = self.notify_socket_from(conf)
  File "/usr/sbin/systemctl", line 1687, in notify_socket_from
    sock.bind(socketfile)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by Exist2Resist** [comment]
In CentOS 7 I built my base docker image using the following command....
`https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py -O /usr/local/bin/systemctl`
then at the end of the docker file the CMD is as follows....
`CMD ["/usr/local/bin/systemctl"]`
The base image loads and stays up.

**Comment by gdraheim** [comment]
I don't know what "systemctl start docker" has to do with systemctl.py. Good luck.
